# Generated by Django 3.2.6 on 2021-08-29 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام محصول')),
                ('photo', models.ImageField(upload_to='images', verbose_name='تصویر')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('hard', models.CharField(max_length=100, verbose_name='طرقیت حافظه داخلی')),
                ('cpu', models.CharField(max_length=100, verbose_name='پردازنده')),
                ('ram', models.IntegerField(verbose_name='ظرفیت حافطه RAM')),
                ('display', models.IntegerField(verbose_name='اندازه صفحه نمایش')),
                ('ram_type', models.CharField(max_length=100, verbose_name='نوع حافظه RAM')),
                ('display_type', models.CharField(max_length=100, verbose_name='دقت صفحه نمایش')),
                ('hard_type', models.CharField(max_length=200, verbose_name='نوع حافظه داخلی')),
            ],
        ),
    ]
